qa: #range NOT implemented
  D0:
    Pt:
      label: '$p_T^D$ [GeV/$c$]'
      bins: [0.,1.,1.5,2.,3.,4.,5.,6.,8.,10.,12.,16.,20.,24.,32.,50.]
      xscale: 'linear'
      yscale: 'symlog'

    EventNumber:
      label: 'Number of the Event on GRID'
      bins: 100
    GridPID:
      label: 'PID on GRID'
      bins: 100
    Eta:
      label: '$\eta$'
      bins: 16
    Phi:
      label: '$\varphi$ [rad]'
      bins: 20
    Y:
      label: 'y'
      bins: 20
    NormDecayLengthXY:
      label: '$L_{XY}/\sigma_{L_{XY}}$'
      bins: [0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1,2,3,4,5,6,7,8,9,10,12,14,16,18,20,40,60,80,100,120,140,160,180,200,400,600,1000]
      xscale: 'symlog'
      yscale: 'symlog'
      linthreshx: 10
    DecayLength:
      label: '$L_{XYZ}$ [cm]'
      bins: [0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1,2,3,4,5,6,7,8,9,10,12,14,16,18,20,40,60,80,100,120,140,160,180,200,400,600,1000]
      xscale: 'symlog'
      yscale: 'symlog'
      linthreshx: 10
    DecayLengthXY:
      label: '$L_{XY}$ [cm]'
      bins: [0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1,2,3,4,5,6,7,8,9,10,12,14,16,18,20,40,60,80,100,120,140,160,180,200,400,600,1000]
      xscale: 'symlog'
      yscale: 'symlog'
      linthreshx: 10
    InvMass:
      label: 'Invariant Mass [GeV/$c$]'
      bins: 50
    CosP:
      label: '$cos(\theta_{point})$'
      bins: [0.5,0.6,0.7,0.8,0.85,0.9,0.91,0.92,0.93,0.94,0.95,0.96,0.97,0.98,0.99,1.0]
      xscale: 'linear'
      yscale: 'symlog'
    CosPXY:
      label: '$cos(\theta_{point})XY$'
      bins: [0.5,0.6,0.7,0.8,0.85,0.9,0.91,0.92,0.93,0.94,0.95,0.96,0.97,0.98,0.99,1.0]
      xscale: 'linear'
      yscale: 'symlog'
    ImpParXY:
      label: '$b_{XY}$ [cm]'
      bins: [0.,0.01,0.02,0.03,0.04,0.05,0.06,0.07,0.08,0.09,0.1,0.2,0.3,0.4,0.5,0.75,1.0,2.0,4.0,10.0,100.]
      xscale: 'symlog'
      yscale: 'symlog'
      linthreshx: 0.1
    DCA:
      label: 'DCA [cm]'
      bins: [0.,0.005,0.01,0.015,0.02,0.025,0.03,0.035,0.04,0.045,0.05,0.075,0.1,0.2,0.3,0.4,0.5,0.75,1.0,2.0,4.0,10.0,100.]
      xscale: 'symlog'
      yscale: 'symlog'
      linthreshx: 0.1
    Normd0MeasMinusExp:
      label: '($d_0^{meas} - d_0^{exp})/\sigma_{\Delta}$'
      bins: [0.,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.5,2.0,3.0,5.0,10.,100.,1000.,10000.]
      xscale: 'symlog'
      yscale: 'symlog'
    CosTs:
      label: '$cos(\theta^{*})$'
      bins: [0.  , 0.02, 0.04, 0.06, 0.08, 0.1 , 0.12, 0.14, 0.16, 0.18, 0.2 , 0.22, 0.24, 0.26, 0.28, 0.3 , 0.32, 0.34, 0.36, 0.38, 0.4 , 0.42, 0.44, 0.46, 0.48, 0.5 , 0.52, 0.54, 0.56, 0.58, 0.6 , 0.62, 0.64, 0.66, 0.68, 0.7 , 0.72, 0.74, 0.76, 0.78, 0.8 , 0.82, 0.84, 0.86, 0.88, 0.9 , 0.92, 0.94, 0.96, 0.98, 1.  , 1.02, 1.04, 1.06, 1.08, 1.1 , 1.12, 1.14, 1.16, 1.18, 1.2 ]
      xscale: 'linear'
      yscale: 'symlog'
    PtDaughter0:
      label: '$p_T^{\pi}$ [GeV/$c$]'
      bins: [0.,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.,1.1,1.2,1.3,1.4,1.5,2.,3.,4.,5.,6.,8.,10.,12.,16.,20.,24.,32.,50.,100.]
      xscale: 'symlog'
      yscale: 'symlog'
    PtDaughter1:
      label: '$p_T^{K}$ [GeV/$c$]'
      bins: [0.,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.,1.1,1.2,1.3,1.4,1.5,2.,3.,4.,5.,6.,8.,10.,12.,16.,20.,24.,32.,50.,100.]
      xscale: 'symlog'
      yscale: 'symlog'
    D0Daughter0:
      label: '$d_0^{\pi}$ [cm]'
      bins: [0.,0.005,0.01,0.02,0.03,0.04,0.05,0.075,0.1,0.2,0.3,0.4,0.5,0.75,1.0,2.0,4.0,10.0,100.]
      xscale: 'symlog'
      yscale: 'symlog'
      linthreshx: 0.1
    D0Daughter1:
      label: '$d_0^{K}$ [cm]'
      bins: [0.,0.005,0.01,0.02,0.03,0.04,0.05,0.075,0.1,0.2,0.3,0.4,0.5,0.75,1.0,2.0,4.0,10.0,100.]
      xscale: 'symlog'
      yscale: 'symlog'
      linthreshx: 0.1
    ReducedChi2:
      label: '$\chi_{red}^2$'
      bins: [0.,0.005,0.01,0.02,0.03,0.04,0.05,0.075,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.1,1.2,1.3,1.4,1.5,1.75,2.0,3.0,4.0,8.0,10.0,50.,100.,200.,500.,1000.,10000]
      xscale: 'symlog'
      yscale: 'symlog'
    SelectionStatus:
      label: 'PID selection status (0 = no, 1 = part, 2 = anti part, 3 = both)'
      bins: [0,1,2,3,4,5]
      logx: false
      logy: false
    D0Prod:
      label: '$d_0^K \times d_0^{\pi}$ [$cm^2$]'
      bins: [-10.,-5.,-4.,-3.,-2.,-1.,-0.1,-0.01,-0.00175,-0.0015,-0.00125,-0.001,-0.0009,-0.0008,-0.0007,-0.0006,-0.00055,-0.0005,-0.00045,-0.0004,-0.00035,-0.0003,-0.0002, -0.0001, .0, 0.0001,0.0002, 0.0003, 0.0004,0.0005,0.0006,0.0007,0.0008,0.0009,0.001,0.00125,0.0015,0.00175, 0.01, 0.1, 2., 3., 4., 5., 10.]
      xscale: 'symlog'
      yscale: 'symlog'
      linthreshx: 0.001
    NSigmaTOFDaughters0:
      label: 'N$\sigma^{TOF}_{\pi}$'
    NSigmaTOFDaughters1:
      label: 'N$\sigma^{TOF}_{K}$'
    NSigmaTPCDaughter1:
      label: 'N$\sigma^{TPC}_{\pi}$'
    NSigmaTPCDaughter0:
      label: 'N$\sigma^{TPC}_{K}$'
    DeltaM:
      label: '$\Delta M$'
      bins: 40
    PtBin:
      label: '$\Delta M$'
      bins: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]

  Electron:
    EventNumber:
      label: 'Number of the Event on GRID'
      bins: 100
    GridPID:
      label: 'PID on GRID'
      bins: 100
    P:
      label: '$p^e$ [GeV/$c$]'
      bins: [0.5, 0.55 ,0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.75,2.0, 2.5, 3.0, 4.0, 5.0, 6.0, 8.0, 10.0]
      xscale: 'linear'
      yscale: 'log'
      linthreshx: 1
    Pt:
      label: '$p_T^e$ [GeV/$c$]'
      bins: [0.2,0.3,0.4,0.5,0.6,0.8,1.0,1.5,2.0,3.0,4.0,6.0,8.0,10.0]
      xscale: 'linear'
      yscale: 'symlog'
      linthreshx: 1
    Eta:
      label: '$\eta$'
      bins: 16
    Phi:
      label: '$\varphi$ [rad]'
      bins: 20
    NClsTPC:
      label: 'Number of Clusters in the TPC'
      bins: [0,10,20,30,40,50,60,70,75,80,85,90,95,100,105,110,115,120,125,130,135,140,145,150,155,160]
    NClsTPCDeDx:
      label: 'Number of Clusters in the TPC used for $dE/dx$'
      bins: [0,10,20,30,40,50,60,70,75,80,85,90,95,100,105,110,115,120,125,130,135,140,145,150,155,160]
    NITSCls:
      label: 'Number of Clusters in the ITS'
      bins: [0,1,2,3,4,5,6]
    DCAxy:
      label: 'Distance of closest approach XY'
      #bins: [0.,0.005,0.01,0.015,0.02,0.025,0.03,0.035,0.04,0.045,0.05,0.075,0.1,0.2,0.3,0.4,0.5,0.75,1.0,1.1,1.2,1.3,1.4,1.5,1.6,1.7,1.8,1.9,2.0,2.2,2.4,2.6,2.8,3.0,3.2,3.4,3.6,3.8,4.0,10.0]
      bins: [0,100,1000,10000.]
      xscale: 'symlog'
      yscale: 'symlog'
      linthreshx: 0.1
    DCAz:
      label: 'Distance of closest approach Z'
      #bins: [0.,0.005,0.01,0.015,0.02,0.025,0.03,0.035,0.04,0.045,0.05,0.075,0.1,0.2,0.3,0.4,0.5,0.75,1.0,1.1,1.2,1.3,1.4,1.5,1.6,1.7,1.8,1.9,2.0,2.2,2.4,2.6,2.8,3.0,3.2,3.4,3.6,3.8,4.0,10.0]
      bins: [0,100,1000,10000.]
      xscale: 'symlog'
      yscale: 'symlog'

    TPCNSigma:
      label: 'TPC $n\sigma^e$'
      bins: [-3.,-2.,-1.,0.,1.,2.,3.]
      yscale: 'symlog'
    TOFNSigma:
      label: 'TOF $n\sigma^e$'
      bins: [-5.,-3.,-2.,-1.,0.,1.,2.,3.,5.]
      yscale: 'symlog'
    NULS:
      label: 'Number of UnLike-Sign partners (ULS)'
      bins: [0,1,2,3,4,5,6,7,8,9,10,12,14,16,18,20]
      yscale: 'symlog'
    NLS:
      label: 'Number of Like-Sign partners (LS)'
      bins: [0,1,2,3,4,5,6,7,8,9,10,12,14,16,18,20]
      yscale: 'symlog'
