correlation:
  bins_assoc: [0.5, 10.]
  bins_trig: [2., 2.25, 2.5, 2.75, 3., 3.5, 4., 4.5, 5., 5.5, 6., 7., 8., 9.0, 10., 11., 12., 14., 16., 20., 24]
  bins_cent: [-10.,100.1]
  bins_zvtx: [-10.01,10.01]
  bins_eta: [-2, 2]
  bins_phi: [-1, 4]
